# Start from the latest golang base image
FROM golang:1.18


WORKDIR /app

# Copy the source from the current directory to the Working Directory inside the container
COPY ../back-end .

# This container exposes port 8080 to the outside world
EXPOSE 8080
